name: mediawiki
version: stable
appVersion: stable
description: MediaWiki is free and open-source wiki software.
icon: https://www.mediawiki.org/static/images/project-logos/mediawikiwiki.png
keywords:
  - wiki
  - web
  - mediawiki
  - application
home: https://www.mediawiki.org/wiki/MediaWiki
sources:
  - https://github.com/wikimedia/mediawiki-docker
maintainers:
  - name: Wikimedia Foundation & Docker Community
engine: gotpl
